using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DataCenterModuleGenerator.Generator;

[Generator]
public class DataCenterModuleGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // 初始化
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // 获取当前语法树
        var syntaxTrees = context.Compilation.SyntaxTrees;
        GenerateDataCenterModuleExecute(context, syntaxTrees);
    }

    #region GenerateDataCenterModule

    private void GenerateDataCenterModuleExecute(GeneratorExecutionContext context, IEnumerable<SyntaxTree> syntaxTrees)
    {
        var moduleTypes = new List<(string className, string namespaceName)>();

        foreach (var tree in syntaxTrees)
        {
            // 获取语法树的根节点
            var root = tree.GetRoot();

            // 获取当前语法树中的所有命名空间节点
            var namespaces = root.DescendantNodes().OfType<NamespaceDeclarationSyntax>();

            // 判断语法树是否在指定检测的命名空间下
            if (namespaces.All(ns => !Definition.TargetNameSpaces.Contains(ns.Name.ToString())))
            {
                continue;
            }

            var classes = GetMatchClasses(root);
            foreach (var classNode in classes)
            {
                var className = classNode.Identifier.Text;
                var namespaceName = GetNamespace(classNode);
                moduleTypes.Add((className, namespaceName));
            }
        }

        if (moduleTypes.Count > 0)
        {
            var scriptContent = GenerateDataCenterModuleCode(moduleTypes);
            context.AddSource($"DataCenterModule_Gen.g.cs", scriptContent);
        }
    }

    private string GenerateDataCenterModuleCode(List<(string className, string namespaceName)> moduleTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// \tThis code was generated by the source generator.");
        sb.AppendLine("// \tChanges to this file may cause incorrect behavior.");
        sb.AppendLine("// \twill be lost if the code is regenerated.");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine();

        sb.AppendLine($"namespace {Definition.NameSpace}");
        {
            sb.AppendLine("{");
            sb.AppendLine($"\tpublic sealed partial class {Definition.TargetClassName}");
            {
                sb.AppendLine("\t{");
                sb.AppendLine();
                sb.AppendLine("\t\tpartial void InitModule()");
                {
                    sb.AppendLine("\t\t{");
                    foreach (var (className, _) in moduleTypes)
                    {
                        sb.AppendLine($"\t\t\tRegisterModule({className}.Instance);");
                    }
                    sb.AppendLine("\t\t}");
                }
                sb.AppendLine();

                sb.AppendLine("\t\t/// <summary>");
                sb.AppendLine("\t\t/// 注册数据中心模块。");
                sb.AppendLine("\t\t/// </summary>");
                sb.AppendLine("\t\t/// <param name=\"module\">要注册的模块</param>");
                sb.AppendLine("\t\tpublic void RegisterModule(IDataCenterModule module)");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tif (m_dataCenterModuleList.Contains(module))");
                    sb.AppendLine("\t\t\t{");
                    sb.AppendLine("\t\t\t\treturn;");
                    sb.AppendLine("\t\t\t}");
                    sb.AppendLine("\t\t\tmodule.OnInit();");
                    sb.AppendLine("\t\t\tm_dataCenterModuleList.Add(module);");
                    sb.AppendLine("\t\t}");
                }
                sb.AppendLine("\t}");
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// 获取匹配的类声明语法（继承了 DataCenterModule 的类）
    /// </summary>
    private IEnumerable<ClassDeclarationSyntax> GetMatchClasses(SyntaxNode root)
        => root.DescendantNodes().OfType<ClassDeclarationSyntax>()
            .Where(c => c.BaseList != null &&
                       c.BaseList.Types.Any(t => t.Type.ToString().StartsWith(Definition.BaseClassName)));

    /// <summary>
    /// 获取类所在的命名空间
    /// </summary>
    private string GetNamespace(ClassDeclarationSyntax classNode)
    {
        var namespaceNode = classNode.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
        return namespaceNode?.Name.ToString() ?? string.Empty;
    }

    #endregion
}