//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using DGame;

namespace GameLogic
{
	public class CommonDesc1WidgetDataComponent : MonoBehaviour
	{
		public Text m_textTest;
		public Text m_textTest1;
	}
}
