//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using DGame;

namespace GameLogic
{
	[DisallowMultipleComponent]
	public class TestWindowDataComponent : MonoBehaviour
	{
		public Button m_btnTest;
		public Text m_textTest;
		public Scrollbar m_scrollBarTest;
		public GameObject m_itemCommonDesc;
		public Transform m_tfGo;
		public GameObject m_itemCommonDesc1;
		public Toggle m_toggleTest;
	}
}
