
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum ColorQuality
    {
        /// <summary>
        /// 无定义颜色占位
        /// </summary>
        COLOR_NONE = 0,
        /// <summary>
        /// 白色
        /// </summary>
        COLOR_WHITE = 1,
        /// <summary>
        /// 绿色
        /// </summary>
        COLOR_GREEN = 2,
        /// <summary>
        /// 蓝色
        /// </summary>
        COLOR_BLUE = 3,
        /// <summary>
        /// 紫色
        /// </summary>
        COLOR_PURPLE = 4,
        /// <summary>
        /// 橙色
        /// </summary>
        COLOR_ORANGE = 5,
        /// <summary>
        /// 红色
        /// </summary>
        COLOR_RED = 6,
        /// <summary>
        /// 彩色
        /// </summary>
        COLOR_CAI = 7,
        /// <summary>
        /// 最大品质，新增+1
        /// </summary>
        COLOR_MAX = 8,
    }

} 

