
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum CommonEffectID
    {
        /// <summary>
        /// 特效1
        /// </summary>
        COMMON_EFFECT_1 = 1,
    }

} 

