
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class EffectConfig : Luban.BeanBase
{
    public EffectConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Location = _buf.ReadString();
        Duration = _buf.ReadFloat();
        Scale = _buf.ReadFloat();
        DelayDestroy = _buf.ReadFloat();
    }

    public static EffectConfig DeserializeEffectConfig(ByteBuf _buf)
    {
        return new EffectConfig(_buf);
    }

    /// <summary>
    /// 特效ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 特效可寻址地址
    /// </summary>
    public readonly string Location;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 缩放比例
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// 延迟销毁时间
    /// </summary>
    public readonly float DelayDestroy;
   
    public const int __ID__ = -682668973;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Location:" + Location + ","
        + "Duration:" + Duration + ","
        + "Scale:" + Scale + ","
        + "DelayDestroy:" + DelayDestroy + ","
        + "}";
    }
}
}

