
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class GmConfig : Luban.BeanBase
{
    public GmConfig(ByteBuf _buf) 
    {
        GmID = _buf.ReadInt();
        GmType = _buf.ReadInt();
        GmDesc = _buf.ReadString();
        GmOrder = _buf.ReadString();
        OrderID = _buf.ReadInt();
        Num = _buf.ReadInt();
        ExecuteDirectly = _buf.ReadInt();
        ExecuteClose = _buf.ReadInt();
        AssConfig = _buf.ReadInt();
    }

    public static GmConfig DeserializeGmConfig(ByteBuf _buf)
    {
        return new GmConfig(_buf);
    }

    /// <summary>
    /// GMID
    /// </summary>
    public readonly int GmID;
    /// <summary>
    /// Gm类型（1:客户端，2:服务器）
    /// </summary>
    public readonly int GmType;
    /// <summary>
    /// 描述（按钮名）
    /// </summary>
    public readonly string GmDesc;
    /// <summary>
    /// GM命令
    /// </summary>
    public readonly string GmOrder;
    /// <summary>
    /// 命令ID
    /// </summary>
    public readonly int OrderID;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Num;
    /// <summary>
    /// 是否直接执行
    /// </summary>
    public readonly int ExecuteDirectly;
    /// <summary>
    /// 是否执行后关闭
    /// </summary>
    public readonly int ExecuteClose;
    /// <summary>
    /// 关联配置
    /// </summary>
    public readonly int AssConfig;
   
    public const int __ID__ = -836822040;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GmID:" + GmID + ","
        + "GmType:" + GmType + ","
        + "GmDesc:" + GmDesc + ","
        + "GmOrder:" + GmOrder + ","
        + "OrderID:" + OrderID + ","
        + "Num:" + Num + ","
        + "ExecuteDirectly:" + ExecuteDirectly + ","
        + "ExecuteClose:" + ExecuteClose + ","
        + "AssConfig:" + AssConfig + ","
        + "}";
    }
}
}

