
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        ItemID = _buf.ReadInt();
        ItemName = _buf.ReadString();
        Quality = (ColorQuality)_buf.ReadInt();
        IconNameMan = _buf.ReadString();
        IconNameWoman = _buf.ReadString();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        if(_buf.ReadBool()){ ExpireTime = _buf.ReadLong(); } else { ExpireTime = null; }
        BatchUseable = _buf.ReadBool();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemID;
    /// <summary>
    /// 道具名字
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 道具品质
    /// </summary>
    public readonly ColorQuality Quality;
    /// <summary>
    /// 图标资源名_男
    /// </summary>
    public readonly string IconNameMan;
    /// <summary>
    /// 图标资源名_女
    /// </summary>
    public readonly string IconNameWoman;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 过期时间
    /// </summary>
    public readonly long? ExpireTime;
    /// <summary>
    /// 能否批量使用
    /// </summary>
    public readonly bool BatchUseable;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "ItemName:" + ItemName + ","
        + "Quality:" + Quality + ","
        + "IconNameMan:" + IconNameMan + ","
        + "IconNameWoman:" + IconNameWoman + ","
        + "Desc:" + Desc + ","
        + "price:" + Price + ","
        + "expireTime:" + ExpireTime + ","
        + "batchUseable:" + BatchUseable + ","
        + "}";
    }
}
}

