
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum LocalizationType
    {
        /// <summary>
        /// 中国
        /// </summary>
        CN = 0,
        /// <summary>
        /// 欧美
        /// </summary>
        EN = 1,
    }

} 

