
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class SoundConfig : Luban.BeanBase
{
    public SoundConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Location = _buf.ReadString();
    }

    public static SoundConfig DeserializeSoundConfig(ByteBuf _buf)
    {
        return new SoundConfig(_buf);
    }

    /// <summary>
    /// 音效ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 音效可寻址地址
    /// </summary>
    public readonly string Location;
   
    public const int __ID__ = -1164338927;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Location:" + Location + ","
        + "}";
    }
}
}

