
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum SysSoundID
    {
        /// <summary>
        /// 背景音乐
        /// </summary>
        BGM = 1000001,
        /// <summary>
        /// 按钮点击
        /// </summary>
        BTN_CLICK = 1000002,
    }

} 

