
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameProto
{
    public partial class Tables
    {
        #region The Tables

        private System.Func<string, ByteBuf> m_defaultLoader;

        /// <summary>
        /// 文本配置表
        /// </summary>
        private TbTextConfig m_TbTextConfig;
        public TbTextConfig TbTextConfig 
        {
            get
            {
                if (m_TbTextConfig == null)
                {
                    m_TbTextConfig = new TbTextConfig(m_defaultLoader("tbtextconfig"));
                    m_TbTextConfig.ResolveRef(this);
                }
                return m_TbTextConfig;
            }
            set
            {
                m_TbTextConfig = value;
                m_TbTextConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 道具配置表
        /// </summary>
        private TbItemConfig m_TbItemConfig;
        public TbItemConfig TbItemConfig 
        {
            get
            {
                if (m_TbItemConfig == null)
                {
                    m_TbItemConfig = new TbItemConfig(m_defaultLoader("tbitemconfig"));
                    m_TbItemConfig.ResolveRef(this);
                }
                return m_TbItemConfig;
            }
            set
            {
                m_TbItemConfig = value;
                m_TbItemConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 音效配置表
        /// </summary>
        private TbSoundConfig m_TbSoundConfig;
        public TbSoundConfig TbSoundConfig 
        {
            get
            {
                if (m_TbSoundConfig == null)
                {
                    m_TbSoundConfig = new TbSoundConfig(m_defaultLoader("tbsoundconfig"));
                    m_TbSoundConfig.ResolveRef(this);
                }
                return m_TbSoundConfig;
            }
            set
            {
                m_TbSoundConfig = value;
                m_TbSoundConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 模型配置表
        /// </summary>
        private TbModelConfig m_TbModelConfig;
        public TbModelConfig TbModelConfig 
        {
            get
            {
                if (m_TbModelConfig == null)
                {
                    m_TbModelConfig = new TbModelConfig(m_defaultLoader("tbmodelconfig"));
                    m_TbModelConfig.ResolveRef(this);
                }
                return m_TbModelConfig;
            }
            set
            {
                m_TbModelConfig = value;
                m_TbModelConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 特效配置表
        /// </summary>
        private TbEffectConfig m_TbEffectConfig;
        public TbEffectConfig TbEffectConfig 
        {
            get
            {
                if (m_TbEffectConfig == null)
                {
                    m_TbEffectConfig = new TbEffectConfig(m_defaultLoader("tbeffectconfig"));
                    m_TbEffectConfig.ResolveRef(this);
                }
                return m_TbEffectConfig;
            }
            set
            {
                m_TbEffectConfig = value;
                m_TbEffectConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// GM配置表
        /// </summary>
        private TbGmConfig m_TbGmConfig;
        public TbGmConfig TbGmConfig 
        {
            get
            {
                if (m_TbGmConfig == null)
                {
                    m_TbGmConfig = new TbGmConfig(m_defaultLoader("tbgmconfig"));
                    m_TbGmConfig.ResolveRef(this);
                }
                return m_TbGmConfig;
            }
            set
            {
                m_TbGmConfig = value;
                m_TbGmConfig.ResolveRef(this);
            }
        }

        #endregion

        public Tables(System.Func<string, ByteBuf> loader)
        {
            SetDefaultLoader(loader);
            Init();
        }

        public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
        {
            m_defaultLoader = null;
            m_defaultLoader = loader;
        }

        public void Init(){}
    }
}
