
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 特效配置表
/// </summary>
public partial class TbEffectConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EffectConfig> _dataMap;
    private readonly System.Collections.Generic.List<EffectConfig> _dataList;
    
    public TbEffectConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EffectConfig>(n);
        _dataList = new System.Collections.Generic.List<EffectConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EffectConfig _v;
            _v = global::GameProto.EffectConfig.DeserializeEffectConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EffectConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EffectConfig> DataList => _dataList;

    public EffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EffectConfig Get(int key) => _dataMap[key];
    public EffectConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

