
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 模型配置表
/// </summary>
public partial class TbModelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ModelConfig> _dataMap;
    private readonly System.Collections.Generic.List<ModelConfig> _dataList;
    
    public TbModelConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ModelConfig>(n);
        _dataList = new System.Collections.Generic.List<ModelConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ModelConfig _v;
            _v = global::GameProto.ModelConfig.DeserializeModelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ModelID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ModelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ModelConfig> DataList => _dataList;

    public ModelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ModelConfig Get(int key) => _dataMap[key];
    public ModelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

