
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 文本配置表
/// </summary>
public partial class TbTextConfig
{
    private readonly System.Collections.Generic.Dictionary<int, TextConfig> _dataMap;
    private readonly System.Collections.Generic.List<TextConfig> _dataList;
    
    public TbTextConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, TextConfig>(n);
        _dataList = new System.Collections.Generic.List<TextConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            TextConfig _v;
            _v = global::GameProto.TextConfig.DeserializeTextConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TextConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<TextConfig> DataList => _dataList;

    public TextConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TextConfig Get(int key) => _dataMap[key];
    public TextConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

