
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class TextConfig : Luban.BeanBase
{
    public TextConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ArgNum = _buf.ReadInt();
        {int __n0 = _buf.ReadSize(); Content = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Content[__index0] = __e0;}}
    }

    public static TextConfig DeserializeTextConfig(ByteBuf _buf)
    {
        return new TextConfig(_buf);
    }

    /// <summary>
    /// 文本ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 参数数量
    /// </summary>
    public readonly int ArgNum;
    /// <summary>
    /// 内容是 string 数组类型，数组索引对应 LocalizationType 枚举
    /// </summary>
    public readonly string[] Content;
   
    public const int __ID__ = -912442641;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ArgNum:" + ArgNum + ","
        + "Content:" + Luban.StringUtil.CollectionToString(Content) + ","
        + "}";
    }
}
}

