//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using DGame;

namespace GameLogic
{
	public partial class m_itemCommonDesc : UIWidget
	{
		#region 脚本工具生成的代码

		private UIBindComponent m_bindComponent;
		private Text m_textTest;
		private Text m_textTest1;

		protected override void ScriptGenerator()
		{
			m_bindComponent = gameObject.GetComponent<UIBindComponent>();
			m_textTest = m_bindComponent.GetComponent<Text>(0);
			m_textTest1 = m_bindComponent.GetComponent<Text>(1);
		}

		#endregion

		#region 事件

		#endregion
	}
}
